#!/usr/bin/env python3
"""Generate demo/index.html — an in-browser engine comparison with audio players.

GitHub strips <audio> from rendered markdown, so links there only download.
This page embeds real <audio controls> players for every demo clip; served via
GitHub Pages (or opened locally) you compare all engines by ear, no code.

    python demo/build_player.py    # reads outputs/ + VERIFICATION.md, writes index.html
"""
import re
from pathlib import Path

DEMO = Path(__file__).resolve().parent
OUT = DEMO / "outputs"

def wer_map():
    m = {}
    vf = DEMO / "VERIFICATION.md"
    if vf.exists():
        for line in vf.read_text().splitlines():
            hit = re.search(r"\[`(?:outputs/)?([^`]+)\.wav`\][^|]*\|\s*(\d+)%", line)
            if hit:
                m[hit.group(1)] = hit.group(2) + "%"
    return m

def main():
    wer = wer_map()
    clips = sorted(p.stem for p in OUT.glob("*.wav") if "_q8" not in p.stem)
    # group by engine (filename = engine__variant)
    engines = {}
    for c in clips:
        eng = c.split("__")[0]
        engines.setdefault(eng, []).append(c)

    def player(rel, label, w=None):
        tag = f' &nbsp;<span class="wer">WER {w}</span>' if w else ""
        return (f'<div class=clip><div class=lbl>{label}{tag}</div>'
                f'<audio controls preload=none src="{rel}"></audio></div>')

    rows = []
    for src in ("source", "reference_aria", "reference_sonia"):
        f = DEMO / f"{src}.wav"
        if f.exists():
            rows.append(player(f"{src}.wav", src.replace("_", " ")))
    inputs = "\n".join(rows)

    cards = []
    for eng in sorted(engines):
        items = "\n".join(
            player(f"outputs/{c}.wav", c.split("__", 1)[1] if "__" in c else c,
                   wer.get(c) or wer.get("outputs/" + c))
            for c in sorted(engines[eng]))
        cards.append(f'<section><h2>{eng}</h2>{items}</section>')

    html = f"""<!doctype html><html lang=en><head><meta charset=utf-8>
<meta name=viewport content="width=device-width,initial-scale=1">
<title>voiceclonnx — engine demos</title><style>
:root{{color-scheme:light dark}}
body{{font:15px/1.5 system-ui,sans-serif;max-width:760px;margin:0 auto;padding:1.5rem 1rem 4rem}}
h1{{margin:.2rem 0}}p.sub{{color:#888;margin-top:0}}
.inputs{{background:#0001;border-radius:10px;padding:.8rem 1rem;margin:1rem 0}}
section{{border:1px solid #8884;border-radius:10px;padding:.6rem 1rem;margin:.8rem 0}}
h2{{margin:.2rem 0 .6rem;font-size:1.05rem;text-transform:capitalize}}
.clip{{display:flex;align-items:center;gap:.8rem;flex-wrap:wrap;margin:.35rem 0}}
.lbl{{min-width:9rem;font-size:.9rem}}.wer{{color:#888;font-variant-numeric:tabular-nums}}
audio{{height:34px;flex:1;min-width:240px}}
</style></head><body>
<h1>voiceclonnx</h1>
<p class=sub>Same sentence, every engine — listen and compare. Pure-ONNX voice conversion.</p>
<div class=inputs><strong>Inputs</strong>{inputs}</div>
{''.join(cards)}
<p class=sub>Generated by <code>demo/build_player.py</code> from <code>demo/outputs/</code> + <code>VERIFICATION.md</code>.</p>
</body></html>"""
    (DEMO / "index.html").write_text(html)
    print(f"wrote demo/index.html — {len(engines)} engines, {len(clips)} clips")

if __name__ == "__main__":
    main()
