#!/usr/bin/env python3
"""STT-verify the bundled demo conversions.

Transcribes every wav in ``outputs/`` (plus the source) with faster-whisper
and scores word error rate against the known source text — a conversion that
preserves intelligibility transcribes close to the original sentence. Writes
``VERIFICATION.md`` with one row per clip so the table doubles as the
listening index.

Run after regenerating demos:
    python demo/verify_demos.py
"""
import re
import sys
from pathlib import Path

DEMO_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(DEMO_DIR.parent))
OUT_DIR = DEMO_DIR / "outputs"

from generate_demos import SOURCE_TEXT  # noqa: E402


def norm(text: str) -> list:
    return re.sub(r"[^a-z' ]", " ", text.lower()).split()


def wer(ref: list, hyp: list) -> float:
    d = [[0] * (len(hyp) + 1) for _ in range(len(ref) + 1)]
    for i in range(len(ref) + 1):
        d[i][0] = i
    for j in range(len(hyp) + 1):
        d[0][j] = j
    for i in range(1, len(ref) + 1):
        for j in range(1, len(hyp) + 1):
            d[i][j] = min(d[i - 1][j] + 1, d[i][j - 1] + 1,
                          d[i - 1][j - 1] + (ref[i - 1] != hyp[j - 1]))
    return d[len(ref)][len(hyp)] / max(len(ref), 1)


def main() -> int:
    from faster_whisper import WhisperModel
    model = WhisperModel("base.en", device="cpu", compute_type="int8")
    ref = norm(SOURCE_TEXT)

    clips = [DEMO_DIR / "source.wav"] + sorted(OUT_DIR.glob("*.wav"))
    rows, failures = [], []
    for wav in clips:
        segments, _ = model.transcribe(str(wav), beam_size=5)
        hyp_text = " ".join(seg.text.strip() for seg in segments)
        score = wer(ref, norm(hyp_text))
        status = "✅" if score <= 0.40 else "❌"
        if score > 0.40 and wav.name != "source.wav":
            failures.append(wav.name)
        rel = wav.relative_to(DEMO_DIR)
        rows.append(f"| [`{rel}`]({rel}) | {score:.0%} | {status} | {hyp_text[:90]} |")
        print(f"[verify] {wav.name}: WER={score:.0%} {status}")

    md = [
        "# Demo verification (generated by verify_demos.py — do not edit)",
        "",
        "Every clip transcribed with faster-whisper `base.en` and scored",
        f"against the known source text (gate: WER ≤ 40%).",
        "",
        "| clip | WER | intelligible | transcript |",
        "|---|---|---|---|",
        *rows,
        "",
    ]
    (DEMO_DIR / "VERIFICATION.md").write_text("\n".join(md))
    print(f"[verify] wrote VERIFICATION.md ({len(rows)} clips, "
          f"{len(failures)} failures: {failures or 'none'})")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
